config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  post "sms", to: "pages#sms"
  post "whatsapp", to: "pages#whatsapp"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, presence: true, uniqueness: true

  before_save :format_phone_number

  private

  def format_phone_number
    self.phone = ApplicationHelper.validate_phone(phone)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def sms
    phone_number = current_user.phone
    message = params[:message]
    TwilioClient.new.send_message(to: phone_number, body: message)
    redirect_to root_path, notice: "SMS sent!"
  end

  def whatsapp
    phone_number = current_user.phone
    message = params[:message]
    TwilioClient.new.send_whatsapp(to: phone_number, body: message)
    redirect_to root_path, notice: "Whatsapp sent!"
  end
end

app/controllers/twilio_controller.rb
# class TwilioController < ApplicationController
#   skip_before_action :verify_authenticity_token
#
#   def webhook
#     webhook_url = url_for(controller: 'twilio', action: 'webhook', only_path: false)
#     Rails.logger.info "Webhook URL: #{webhook_url}"
#
#     from = params[:From]
#     body = params[:Body]
#
#     forward_to_number = current_user.phone
#
#     TwilioClient.new.send_message(to: forward_to_number, body: "From #{from}: #{body}")
#
#     head :ok
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.validate_phone(phone_number)
    # Remove todos os traços
    phone_number.gsub!('-', '')

    # Remove o primeiro 0, se existir
    phone_number.sub!(/^0/, '')

    # Adiciona +81 no início, se não existir
    phone_number.prepend('+81') unless phone_number.start_with?('+81')

    phone_number
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessengerUInnova</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<h1 class="mb-4">Sending Messages</h1>

<% if user_signed_in? %>
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">To: <%= current_user.phone %></h5>

      <%= form_with url: sms_path, method: :post, local: true, class: 'mb-3' do %>
        <div class="form-group">
          <label for="message">Escreva sua Mensagem:</label>
          <%= text_field_tag :message, nil, class: 'form-control', required: true %>
        </div>
        <br>
        <%= submit_tag "Enviar SMS", class: 'btn btn-primary', data: { confirm: 'Tem certeza que deseja enviar a mensagem?' } %>
      <% end %>

      <%= form_with url: whatsapp_path, method: :post, local: true do %>
        <div class="form-group">
          <label for="message">Escreva sua Mensagem:</label>
          <%= text_field_tag :message, nil, class: 'form-control', required: true %>
        </div>
        <br>
        <%= submit_tag "Enviar Whatsapp", class: 'btn btn-success', data: { confirm: 'Tem certeza que deseja enviar a mensagem?' } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/cassianotadaoyasumitsu", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>